### ISSUE TITLE
please add this new paper: NRL on Event Graph

### ISSUE THREAD

**Issue by eecrazy** [thunlp/NRLPapers#16]
Constructing Narrative Event Evolutionary Graph for Script Event Prediction, from HIT-SCIR
This paper has been accepted by IJCAI 2018, and has been presented at AIS in Beijing.
You can find the paper here:  https://arxiv.org/abs/1805.05081
and the code is here: https://github.com/eecrazy/ConstructingNEEG_IJCAI_2018, more materials such ppt and poster can be found at http://ir.hit.edu.cn/~zyli/

**Comment by zzy14** [comment]
Thanks.
