### ISSUE TITLE
Add a link to the source code of paper 108. ANRL: Attributed Network Representation Learning via Deep Neural Networks

### ISSUE THREAD

**Issue by DwyaneSuarez** [thunlp/NRLPapers#25]
Paper 108, ANRL, has source code in the link [https://github.com/cszhangzhen/ANRL](https://github.com/cszhangzhen/ANRL)

**Comment by jayzzhou-thu** [comment]
Hi @DwyaneSuarez, the link has been added, thanks for your contribution!
