### ISSUE TITLE
Add more papers?

### ISSUE THREAD

**Issue by mrmotallebi** [thunlp/NRLPapers#26]
For example, GraphSAGE by SNAP @ Stanford : http://snap.stanford.edu/graphsage/
and this guy's works if you like: https://cs.stanford.edu/people/rexy/

**Comment by jayzzhou-thu** [comment]
Hi @mrmotallebi, these papers have been added to our GNN paper list (https://github.com/thunlp/gnnpapers). Thanks for your recommendation.
