### ISSUE TITLE
Please add KDD 2019 paper, data, code

### ISSUE THREAD

**Issue by srijankr** [thunlp/NRLPapers#28]
Hi!

Thank you for this awesome repository!

Could you please add the following paper, code, and data link to the repository:
Paper: Predicting Dynamic Embedding Trajectory in Temporal Interaction Networks
Authors: Srijan Kumar, Xikun Zhang, Jure Leskovec
Venue: ACM SIGKDD 2019 (Proceedings of the 25th ACM SIGKDD international conference on Knowledge discovery and data mining)
Project page: http://snap.stanford.edu/jodie/
Code: https://github.com/srijankr/jodie/
All datasets: http://snap.stanford.edu/jodie/

Many thanks,
Srijan

**Comment by jayzzhou-thu** [comment]
Hi @srijankr, the paper has been added, thanks for your contribution!
