### ISSUE TITLE
Please add the following KDD 2019 paper

### ISSUE THREAD

**Issue by ahmedrashed-ml** [thunlp/NRLPapers#30]
Hi

Could you please add the following paper to the repository:

Rashed, Ahmed, Josif Grabocka, and Lars Schmidt-Thieme. "Multi-Relational Classification via Bayesian Ranked Non-Linear Embeddings." Proceedings of the 25th ACM SIGKDD International Conference on Knowledge Discovery & Data Mining. ACM, 2019.

Many thanks,
Ahmed

**Comment by jayzzhou-thu** [comment]
Hi @ahmedrashed-ml, the paper has been added, thanks for your contribution!
