### ISSUE TITLE
关于NRL与KRL的区别

### ISSUE THREAD

**Issue by penelope24** [thunlp/NRLPapers#9]
首先感谢你们做了这么赞的论文整理，对于初学者简直太友好了。
但是我一直有一个问题，就是NRL和KRL不是都是对网络结构的表征学习吗？虽然KRL有提取三元组的操作，但是感觉本质上也是对网络结构的一种抽象。那么这两类论文的区别到底在哪里呢，望不吝赐教！

**Comment by 27232xsl** [comment]
你好，我也有这个疑问，请问你现在搞明白了吗？

**Comment by talorwu** [comment]
我理解，NRL是一个通用的概念，起源于同质网络，但是目前也包括对异质网路的研究；KRL主要针对异质网络，特别地，是针对KG这种特殊的大规模异质网络。

**Comment by 27232xsl** [comment]
哦这样啊，那感觉KRL更适合我，谢谢你
